server:
  port:
    10003
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ag_auth_v1?useUnicode-true&characterEncodeing=UTF8
    type: com.alibaba.druid.pool.DruidDataSource
    name: ag_auth_v1

